extensions = ["dockerfile"]
filenames = ["Dockerfile", "Containerfile"]
aliases = ["docker"]

[source]
repo = "https://github.com/camdencheek/tree-sitter-dockerfile"
rev = "971acdd908568b4531b0ba28a445bf0bb720aba5"
license = "MIT"
