extensions = ["dot", "gv"]
aliases = ["graphviz"]
comment = "//"
comment_block = ["/*", "*/"]

[source]
repo = "https://github.com/rydesun/tree-sitter-dot"
rev = "80327abbba6f47530edeb0df9f11bd5d5c93c14d"
license = "MIT"
