extensions = ["html", "htm", "xhtml"]
comment_block = ["<!--", "-->"]

[source]
repo = "https://github.com/tree-sitter/tree-sitter-html"
rev = "73a3947324f6efddf9e17c0ea58d454843590cc0"
license = "MIT"
