extensions = ["cs", "csx"]
aliases = ["cs"]
symbol = "tree_sitter_c_sharp"
comment = "//"
comment_block = ["/*", "*/"]

[source]
repo = "https://github.com/tree-sitter/tree-sitter-c-sharp"
rev = "9150f7d56bb47f1a809fa23623f1ba1413e93fa9"
license = "MIT"
