extensions = ["scala", "sc", "sbt"]
comment = "//"
comment_block = ["/*", "*/"]

[source]
repo = "https://github.com/tree-sitter/tree-sitter-scala"
rev = "db390f312a54b04b13790e1767bfac32665c17ac"
license = "MIT"
