extensions = ["erb"]
symbol = "tree_sitter_embedded_template"

[source]
repo = "https://github.com/tree-sitter/tree-sitter-embedded-template"
rev = "3499d85f0a0d937c507a4a65368f2f63772786e1"
license = "MIT"
