extensions = ["purs"]
comment = "--"
comment_block = ["{-", "-}"]

[source]
repo = "https://github.com/postsolar/tree-sitter-purescript"
rev = "f541f95ffd6852fbbe88636317c613285bc105af"
license = "MIT"
