extensions = ["dts", "dtsi"]
comment = "//"
comment_block = ["/*", "*/"]

[source]
repo = "https://github.com/joelspadin/tree-sitter-devicetree"
rev = "e78bf56f206cb47bee28a217423acb651e076848"
license = "MIT"
