extensions = ["odin"]
comment = "//"
comment_block = ["/*", "*/"]
indent_style = "tab"
indent_size = 4

[source]
repo = "https://github.com/tree-sitter-grammars/tree-sitter-odin"
rev = "d2ca8efb4487e156a60d5bd6db2598b872629403"
license = "MIT"
